### ISSUE TITLE
missing header file

### ISSUE THREAD

**Issue by mkeyno** [piettetech/PietteTech_DHT#8]
hi, I use DHT21 with arduino pro mini but I find the following file is missing , do you have any idea what is necessary to compile it

https://github.com/piettetech/PietteTech_DHT/blob/master/firmware/PietteTech_DHT.cpp#L46

**Comment by mtnscott** [comment]
I'm sorry for the late reply.  It's not clear what your problem is.  The firmware/examples directory has sample code that can be used with the Spark / Photon systems.  I don't know if they will compile on the Arduino Pro Mini.  You should just be able to use the library files - 
PietteTech_DHT.cpp
PietteTech_DHT.h

The examples demonstrate how to use the library.

Hope this helps!
